server:
  port: 8100

eureka:
  instance:
    hostname: server1
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://yjmyzz:123456@server2:8200/eureka,http://yjmyzz:123456@server3:8300/eureka
