spring:
  application:
    name: "service-provider"
  profiles:
    active: port1
#  cloud:
#    stream:
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers: localhost
#          zkNodes: localhost
#          defaultZkPort: 2181
#          defaultBrokerPort: 9092

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://yjmyzz:123456@server1:8100/eureka,http://yjmyzz:123456@server2:8200/eureka

security:
  basic:
    enabled: true
  user:
    name: app01
    password: passwd01

management:
  security:
    enabled: false

logging:
  level:
   root: INFO
   org.springframework.cloud.sleuth: DEBUG
